//
//  ProductListPresenterTests.swift
//  iOSAssignment
//
//  Created by David Velarde on 18/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import iOSAssignment
import XCTest

class ProductListPresenterTests: XCTestCase {
    // MARK: Subject under test
  
    var sut: ProductListPresenter!
  
    // MARK: Test lifecycle
  
    override func setUp() {
        super.setUp()
        setupProductListPresenter()
    }
  
    override func tearDown() {
        super.tearDown()
    }
  
    // MARK: Test setup
  
    func setupProductListPresenter() {
        sut = ProductListPresenter()
    }
  
    // MARK: Test doubles
  
    class ProductListDisplayLogicSpy: ProductListDisplayLogic {
        var displaySomethingCalled = false
    
        func displaySomething(viewModel: ProductList.Something.ViewModel) {
            displaySomethingCalled = true
        }
    }
  
    // MARK: Tests
  
    func testPresentSomething() {
        // Given
        let spy = ProductListDisplayLogicSpy()
        sut.viewController = spy
        let response = ProductList.Something.Response()
    
        // When
        sut.presentSomething(response: response)
    
        // Then
        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
