//
//  WelcomeViewController.swift
//  iOSAssignment
//
//  Created by David Velarde on 18/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class WelcomeViewController: UIViewController {
  
    var router: (NSObjectProtocol & WelcomeRoutingLogic & WelcomeDataPassing)?
    let welcomeView = WelcomeView(frame: .zero)

    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    // MARK: Setup
  
    override func loadView() {
        view = welcomeView
    }
    
    private func setup() {
        let viewController = self
        let router = WelcomeRouter()
        viewController.router = router
        router.viewController = viewController
    }
  
    // MARK: View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        
        welcomeView.goToProductListButton.addTarget(self, action: #selector(didTapOnGoToProductListButton), for: .touchUpInside)
    }
    
    @objc func didTapOnGoToProductListButton(sender: UIButton) {
        router?.routeToProductList()
    }
}
