//
//  ProductListPresenter.swift
//  iOSAssignment
//
//  Created by David Velarde on 18/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductListPresentationLogic {
    func presentSomething(response: ProductList.Something.Response)
}

class ProductListPresenter: ProductListPresentationLogic {
    weak var viewController: ProductListDisplayLogic?
  
    // MARK: Do something
  
    func presentSomething(response: ProductList.Something.Response) {
        let viewModel = ProductList.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
