//
//  ProductListWorker.swift
//  iOSAssignment
//
//  Created by David Velarde on 18/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductListWorkerInterface {
    func getProducts(start: Int, end: Int) -> Products
}

struct ProductListWorker: ProductListWorkerInterface {
    
    var productRepository: ProductsRepositoryType = ProductsRepository()
    
    func getProducts(start: Int, end: Int) -> Products {
        return Products(products: [ProductRaw]())
    }
}
