//
//  ProductListViewController.swift
//  iOSAssignment
//
//  Created by David Velarde on 18/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductListDisplayLogic: AnyObject {
    func listProducts(viewModel: ProductList.ListProducts.ViewModel)
    func startProductInteraction(viewModel: ProductList.StartProductInteraction.ViewModel)
    func finishProductInteraction(viewModel: ProductList.FinishProductInteraction.ViewModel)
    func updateProductCell(viewModel: ProductList.CartUpdate.ViewModel)
}

class ProductListViewController: UIViewController, ProductListDisplayLogic {
    
    var interactor: ProductListBusinessLogic?
    
    var products = [CartProduct]()
    let productListView = ProductListView(frame: .zero)

    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    // MARK: Setup
  
  
    private func setup() {
        let viewController = self
        let interactor = ProductListInteractor()
        let presenter = ProductListPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }
  
    // MARK: View lifecycle
    
    override func loadView() {
        self.view = productListView
    }
  
    override func viewDidLoad() {
        super.viewDidLoad()
        
        productListView.tableView.register(ProductCell.self, forCellReuseIdentifier: ProductCell.identifier)
        productListView.tableView.dataSource = self
        
        loadData()
    }
  
    // MARK: Do something
    
    func loadData() {
        let request = ProductList.InitialLoad.Request()
        interactor?.initialLoad(request: request)
    }
    
    @objc func addProductToCart(index: Int) {
        let request = ProductList.CartUpdate.Request(productIndex: index, type: .add)
        interactor?.updateCart(request: request)
    }
    
    @objc func removeProductFromCart(index: Int) {
        let request = ProductList.CartUpdate.Request(productIndex: index, type: .remove)
        interactor?.updateCart(request: request)
    }
    
    func listProducts(viewModel: ProductList.ListProducts.ViewModel) {
        products = viewModel.products
    }
    
    func startProductInteraction(viewModel: ProductList.StartProductInteraction.ViewModel) {
        
        let productCell = ProductCellDecorator.getCurrentCell(tableView: productListView.tableView, indexPath: IndexPath(row: viewModel.index, section: 0))
        productCell?.updateState(.interaction, animated: true)
    }
    
    func finishProductInteraction(viewModel: ProductList.FinishProductInteraction.ViewModel) {
        
        let productCell = ProductCellDecorator.getCurrentCell(tableView: productListView.tableView, indexPath: IndexPath(row: viewModel.index, section: 0))
        productCell?.updateState(.normal, animated: true)
    }
    
    func updateProductCell(viewModel: ProductList.CartUpdate.ViewModel) {
        guard let productCell = ProductCellDecorator.getCurrentCell(tableView: productListView.tableView, indexPath: IndexPath(row: viewModel.index, section: 0)) else { return }
        
        let product = products[viewModel.index]
        ProductCellDecorator.updateCellAmount(cell: productCell, product: product)
    }
}

extension ProductListViewController: UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return products.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = ProductCellDecorator.dequeueProductCell(tableView: tableView, indexPath: indexPath) else {
            return UITableViewCell()
        }
        let product = products[indexPath.row]
        ProductCellDecorator.setupProductCell(cell: cell, indexPath: indexPath, product: product, delegate: self)
        return cell
    }
}

extension ProductListViewController: AddCartDelegate {
    func didStartInteraction(indexPath: IndexPath) {
        let request = ProductList.ProductInteraction.Request(index: indexPath.row)
        interactor?.startProductInteraction(request: request)
    }
    
    func didAddToCart(indexPath: IndexPath) {
        let request = ProductList.CartUpdate.Request(productIndex: indexPath.row, type: .add)
        interactor?.updateCart(request: request)
    }
    
    func didRemoveFromCart(indexPath: IndexPath) {
        let request = ProductList.CartUpdate.Request(productIndex: indexPath.row, type: .remove)
        interactor?.updateCart(request: request)
    }
}
