//
//  ProductListRouter.swift
//  iOSAssignment
//
//  Created by David Velarde on 18/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductListRoutingLogic {
    func routeToWelcome()
}

protocol ProductListDataPassing { }

class ProductListRouter: NSObject, ProductListRoutingLogic, ProductListDataPassing {
    weak var viewController: ProductListViewController?
    var dataStore: ProductListDataStore?
  
    func routeToWelcome() {
        
    }
    
//    // MARK: Routing
//    func routeToSomewhere(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            let destinationVC = segue.destination as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
//        }
//    }
//
//    // MARK: Navigation
//    func navigateToSomewhere(source: ProductListViewController, destination: SomewhereViewController) {
//        source.show(destination, sender: nil)
//    }
//
//    // MARK: Passing data
//    func passDataToSomewhere(source: ProductListDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
