//
//  ProductListInteractor.swift
//  iOSAssignment
//
//  Created by David Velarde on 18/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductListBusinessLogic {
    func initialLoad(request: ProductList.InitialLoad.Request)
    func startProductInteraction(request: ProductList.ProductInteraction.Request)
    func updateCart(request: ProductList.CartUpdate.Request)
}

protocol ProductListDataStore {
    //var name: String { get set }
}

class ProductListInteractor: ProductListBusinessLogic, ProductListDataStore {
    
    var presenter: ProductListPresentationLogic?
    
    var products = [ProductRaw]()
    
    lazy var productListWorker: ProductListWorkerInterface = {
        return ProductListWorker()
    }()
    
    lazy var cartWorker: CartWorkerInterface = {
        return CartWorker()
    }()
    
    var isLoading = false
  
    // MARK: Do something
  
    func initialLoad(request: ProductList.InitialLoad.Request) {
        
        isLoading = true
        
        productListWorker.getProducts(start: products.count, amount: 10) { [weak self] products in
            self?.products.append(contentsOf: products.products)
            self?.isLoading = false
            self?.listProducts()
        }
    }
    
    func updateCart(request: ProductList.CartUpdate.Request) {
        
        guard request.productIndex < products.count else {
            return
        }
        
        let product = products[request.productIndex]
        
        switch request.type {
        case .add:
            cartWorker.addProductToCart(product: product)
        case .remove:
            cartWorker.removeProductFromCart(product: product)
        }
        
        listProducts()
    }
    
    func startProductInteraction(request: ProductList.ProductInteraction.Request) {
        
    }
    
    private func listProducts() {
        let response = ProductList.ListProducts.Response(products: products, cartProducts: cartWorker.cartProducts)
        presenter?.listProducts(response: response)
    }
}
