//
//  WelcomeInteractorTests.swift
//  iOSAssignment
//
//  Created by David Velarde on 18/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import iOSAssignment
import XCTest

class WelcomeInteractorTests: XCTestCase {
    // MARK: Subject under test
  
    var sut: WelcomeInteractor!
  
    // MARK: Test lifecycle
  
    override func setUp() {
        super.setUp()
        setupWelcomeInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
  
    // MARK: Test setup
  
    func setupWelcomeInteractor() {
        sut = WelcomeInteractor()
    }
  
    // MARK: Test doubles
  
    class WelcomePresentationLogicSpy: WelcomePresentationLogic {
        var presentSomethingCalled = false
    
        func presentSomething(response: Welcome.Something.Response) {
            presentSomethingCalled = true
        }
    }
  
    // MARK: Tests
  
    func testDoSomething() {
        // Given
        let spy = WelcomePresentationLogicSpy()
        sut.presenter = spy
        let request = Welcome.Something.Request()
    
        // When
        sut.doSomething(request: request)
    
        // Then
        XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
    }
}
