//
//  WelcomePresenterTests.swift
//  iOSAssignment
//
//  Created by David Velarde on 18/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import iOSAssignment
import XCTest

class WelcomePresenterTests: XCTestCase {
    // MARK: Subject under test
  
    var sut: WelcomePresenter!
  
    // MARK: Test lifecycle
  
    override func setUp() {
        super.setUp()
        setupWelcomePresenter()
    }
  
    override func tearDown() {
        super.tearDown()
    }
  
    // MARK: Test setup
  
    func setupWelcomePresenter() {
        sut = WelcomePresenter()
    }
  
    // MARK: Test doubles
  
    class WelcomeDisplayLogicSpy: WelcomeDisplayLogic {
        var displaySomethingCalled = false
    
        func displaySomething(viewModel: Welcome.Something.ViewModel) {
            displaySomethingCalled = true
        }
    }
  
    // MARK: Tests
  
    func testPresentSomething() {
        // Given
        let spy = WelcomeDisplayLogicSpy()
        sut.viewController = spy
        let response = Welcome.Something.Response()
    
        // When
        sut.presentSomething(response: response)
    
        // Then
        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
