//
//  WelcomeWorkerTests.swift
//  iOSAssignment
//
//  Created by David Velarde on 18/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import iOSAssignment
import XCTest

class WelcomeWorkerTests: XCTestCase {
  
    // MARK: Subject under test
    
    var sut: WelcomeWorker!
    
    // MARK: Test lifecycle
  
    override func setUp() {
        super.setUp()
        setupWelcomeWorker()
    }
  
    override func tearDown() {
        super.tearDown()
    }
  
    // MARK: Test setup
  
    func setupWelcomeWorker() {
        sut = WelcomeWorker()
    }
  
    // MARK: Test doubles
  
    // MARK: Tests
  
    func testSomething() {
        // Given
    
        // When
    
        // Then
    }
}
