//
//  WelcomeViewControllerTests.swift
//  iOSAssignment
//
//  Created by David Velarde on 18/12/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import iOSAssignment
import XCTest

class WelcomeViewControllerTests: XCTestCase {

    // MARK: Subject under test
  
    var sut: WelcomeViewController!
    var window: UIWindow!
  
    // MARK: Test lifecycle
  
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupWelcomeViewController()
    }
  
    override func tearDown() {
        window = nil
        super.tearDown()
    }
  
    // MARK: Test setup
  
    func setupWelcomeViewController() {
        sut = WelcomeViewController()
    }
  
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
  
    // MARK: Test doubles
  
    class WelcomeBusinessLogicSpy: WelcomeBusinessLogic {
        var doSomethingCalled = false
    
        func doSomething(request: Welcome.Something.Request) {
            doSomethingCalled = true
        }
    }
  
    // MARK: Tests
  
    func testShouldDoSomethingWhenViewIsLoaded() {
        // Given
        let spy = WelcomeBusinessLogicSpy()
        sut.interactor = spy
    
        // When
        loadView()
    
        // Then
        XCTAssertTrue(spy.doSomethingCalled, "viewDidLoad() should ask the interactor to do something")
    }
  
    func testDisplaySomething() {
        // Given
        let viewModel = Welcome.Something.ViewModel()
    
        // When
        loadView()
        sut.displaySomething(viewModel: viewModel)
    
        // Then
        //XCTAssertEqual(sut.nameTextField.text, "", "displaySomething(viewModel:) should update the name text field")
    }
}
